### ISSUE TITLE
请问下数据从哪里获取的

### ISSUE THREAD

**Issue by MuYunyun** [hishark/2021#1]
请问下楼主, 😄 
1. 比如专注的数据是从哪里获取的?
2. 表格数据当前是自动还是手动更新的呀?

**Comment by hishark** [comment]
手动的～用的 Echarts 里面的热力图喔。

最近忙着写论文还没空折腾自动化，就先开个仓库手动记录下，之后忙完折腾下自动化的流程哈哈。

**Comment by yihong0618** [comment]
> 请问下楼主, 😄 
> 
> 1. 比如专注的数据是从哪里获取的?
> 
> 2. 表格数据当前是自动还是手动更新的呀?
> 
> 

自动的可以用我这个～

https://github.com/yihong0618/GitHubPoster

**Comment by MuYunyun** [comment]
> > 请问下楼主, 😄
> > 
> > 1. 比如专注的数据是从哪里获取的?
> > 2. 表格数据当前是自动还是手动更新的呀?
> 
> 自动的可以用我这个～
> 
> https://github.com/yihong0618/GitHubPoster

👍

**Comment by yihong0618** [comment]
@MuYunyun 

其中早起我利用的是 GitHub Actions + shortcuts. (关闭闹钟触发)

代码可以参考 ---
https://github.com/yihong0618/2021/blob/main/get_up.py

其它的可以利用 api 或者用 issue.

**Comment by hishark** [comment]
> @MuYunyun
> 
> 其中早起我利用的是 GitHub Actions + shortcuts. (关闭闹钟触发)
> 
> 代码可以参考 ---
> https://github.com/yihong0618/2021/blob/main/get_up.py
> 
> 其它的可以利用 api 或者用 issue.

yihong 稳的哈哈哈 😉
